"""Course-oriented diagnostics for the SME AI workflow adoption project.

This script complements ``enhanced_training_gpu.py``. The enhanced script is the
full prediction pipeline; this file produces teaching-friendly outputs for the
machine-learning course report: OLS coefficients, VIF diagnostics, and a compact
algorithm comparison table.

The script consumes only processed Eurostat panels generated by the acquisition
and cleaning pipelines. It does not synthesize or fabricate observations.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd
import statsmodels.api as sm
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import ExtraTreesRegressor, RandomForestRegressor
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LinearRegression, Ridge
from sklearn.metrics import mean_absolute_error, r2_score
from sklearn.model_selection import GroupKFold
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from statsmodels.stats.outliers_influence import variance_inflation_factor


ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data" / "processed"
OUT = ROOT / "outputs"
TABLES = OUT / "tables"
REPORTS = OUT / "reports"
TABLES.mkdir(parents=True, exist_ok=True)
REPORTS.mkdir(parents=True, exist_ok=True)

TARGET = "target_workflow_automation"
RANDOM_STATE = 42

DATASETS = [
    {
        "name": "Stage 1 SME规模层",
        "path": DATA / "eurostat_multisource_panel.csv",
        "group": "geo",
        "features": [
            "ai__E_AI_TML",
            "ai__E_AI_TNLG",
            "deployment_readiness_index",
            "data_maturity_index",
            "digital_foundation_index",
            "market_digitization_index",
            "ict_constraint_index",
            "governance_maturity_proxy",
            "cloud__E_CC_PDEV",
            "cloud__E_CC_DA",
        ],
    },
    {
        "name": "Stage 2 行业验证层",
        "path": DATA / "stage2_industry_panel.csv",
        "group": "geo",
        "features": [
            "deployment_readiness_index",
            "data_maturity_index",
            "digital_foundation_index",
            "market_digitization_index",
            "ict_constraint_index",
            "governance_maturity_proxy",
            "ai_industry__E_AI_TML",
            "ai_industry__E_AI_TNLG",
            "security_concern_index",
            "isoc_cicce_usen2__E_CC",
        ],
    },
]

FEATURE_LABELS = {
    "ai__E_AI_TML": "机器学习能力",
    "ai__E_AI_TNLG": "自然语言生成",
    "deployment_readiness_index": "部署准备度",
    "data_maturity_index": "数据成熟度",
    "digital_foundation_index": "数字基础",
    "market_digitization_index": "市场数字化",
    "ict_constraint_index": "ICT人才约束",
    "governance_maturity_proxy": "治理成熟度",
    "cloud__E_CC_PDEV": "云开发能力",
    "cloud__E_CC_DA": "云数据分析",
    "ai_industry__E_AI_TML": "行业机器学习能力",
    "ai_industry__E_AI_TNLG": "行业自然语言生成",
    "security_concern_index": "安全顾虑指数",
    "isoc_cicce_usen2__E_CC": "行业云使用",
}


def load_frame(spec: dict) -> pd.DataFrame:
    df = pd.read_csv(spec["path"])
    if TARGET not in df.columns:
        target_candidates = [c for c in ["ai__E_AI_TPA", "ai_industry__E_AI_TPA"] if c in df.columns]
        if not target_candidates:
            raise ValueError(f"{spec['name']} has no target column")
        df[TARGET] = df[target_candidates[0]]
    keep = [TARGET, spec["group"], *[c for c in spec["features"] if c in df.columns]]
    out = df[keep].copy()
    out = out[out[TARGET].notna()]
    return out


def ols_diagnostics(spec: dict, df: pd.DataFrame) -> tuple[dict, list[dict], list[dict]]:
    features = [c for c in spec["features"] if c in df.columns]
    X = df[features].copy()
    X = X.fillna(X.median(numeric_only=True))
    y = df[TARGET].astype(float)

    scaler = StandardScaler()
    Xs = pd.DataFrame(scaler.fit_transform(X), columns=features, index=X.index)
    model = sm.OLS(y, sm.add_constant(Xs)).fit()

    summary_row = {
        "dataset": spec["name"],
        "n": int(model.nobs),
        "r2": float(model.rsquared),
        "adj_r2": float(model.rsquared_adj),
        "aic": float(model.aic),
        "bic": float(model.bic),
        "features": len(features),
        "significant_05": int((model.pvalues.drop("const") < 0.05).sum()),
    }
    coef_rows = []
    for feature in features:
        coef_rows.append(
            {
                "dataset": spec["name"],
                "feature": feature,
                "feature_label": FEATURE_LABELS.get(feature, feature),
                "coef_std": float(model.params[feature]),
                "std_err": float(model.bse[feature]),
                "t": float(model.tvalues[feature]),
                "p_value": float(model.pvalues[feature]),
                "significant_05": bool(model.pvalues[feature] < 0.05),
                "direction": "positive" if model.params[feature] >= 0 else "negative",
            }
        )

    vif_rows = []
    Xv = sm.add_constant(Xs)
    for i, feature in enumerate(Xv.columns):
        if feature == "const":
            continue
        vif_rows.append(
            {
                "dataset": spec["name"],
                "feature": feature,
                "feature_label": FEATURE_LABELS.get(feature, feature),
                "vif": float(variance_inflation_factor(Xv.values, i)),
            }
        )
    return summary_row, coef_rows, vif_rows


def algorithm_comparison(spec: dict, df: pd.DataFrame) -> list[dict]:
    features = [c for c in spec["features"] if c in df.columns]
    X = df[features]
    y = df[TARGET].astype(float)
    groups = df[spec["group"]]
    pre = ColumnTransformer(
        [
            ("num", Pipeline([("imputer", SimpleImputer(strategy="median")), ("scaler", StandardScaler())]), features),
            ("cat", Pipeline([("imputer", SimpleImputer(strategy="most_frequent")), ("onehot", OneHotEncoder(handle_unknown="ignore"))]), []),
        ],
        verbose_feature_names_out=False,
    )
    models = {
        "多元线性回归": LinearRegression(),
        "岭回归": Ridge(alpha=5.0),
        "随机森林": RandomForestRegressor(n_estimators=400, min_samples_leaf=3, random_state=RANDOM_STATE, n_jobs=-1),
        "ExtraTrees": ExtraTreesRegressor(n_estimators=500, min_samples_leaf=2, random_state=RANDOM_STATE, n_jobs=-1),
    }

    rows = []
    cv = GroupKFold(n_splits=5)
    for name, estimator in models.items():
        fold_r2, fold_mae, train_r2 = [], [], []
        for train_idx, test_idx in cv.split(X, y, groups):
            pipe = Pipeline([("prep", pre), ("model", estimator)])
            pipe.fit(X.iloc[train_idx], y.iloc[train_idx])
            pred = pipe.predict(X.iloc[test_idx])
            train_pred = pipe.predict(X.iloc[train_idx])
            fold_r2.append(r2_score(y.iloc[test_idx], pred))
            fold_mae.append(mean_absolute_error(y.iloc[test_idx], pred))
            train_r2.append(r2_score(y.iloc[train_idx], train_pred))
        rows.append(
            {
                "dataset": spec["name"],
                "model_cn": name,
                "r2_mean": float(np.mean(fold_r2)),
                "r2_std": float(np.std(fold_r2)),
                "mae_mean": float(np.mean(fold_mae)),
                "train_r2_mean": float(np.mean(train_r2)),
                "feature_count": len(features),
                "validation": "GroupKFold by country",
            }
        )
    return rows


def main() -> None:
    summary_rows, coef_rows, vif_rows, alg_rows = [], [], [], []
    for spec in DATASETS:
        df = load_frame(spec)
        summary, coefs, vifs = ols_diagnostics(spec, df)
        summary_rows.append(summary)
        coef_rows.extend(coefs)
        vif_rows.extend(vifs)
        alg_rows.extend(algorithm_comparison(spec, df))

    pd.DataFrame(summary_rows).to_csv(TABLES / "course_regression_summary.csv", index=False, encoding="utf-8-sig")
    pd.DataFrame(coef_rows).to_csv(TABLES / "course_ols_coefficients.csv", index=False, encoding="utf-8-sig")
    pd.DataFrame(vif_rows).to_csv(TABLES / "course_vif_diagnostics.csv", index=False, encoding="utf-8-sig")
    pd.DataFrame(alg_rows).to_csv(TABLES / "course_algorithm_comparison.csv", index=False, encoding="utf-8-sig")

    report = ["# Course ML Diagnostics Report", ""]
    report.append("## OLS Summary")
    report.append(pd.DataFrame(summary_rows).to_markdown(index=False))
    report.append("")
    report.append("## Algorithm Comparison")
    report.append(pd.DataFrame(alg_rows).to_markdown(index=False))
    report.append("")
    report.append("## Top OLS Coefficients")
    coef_df = pd.DataFrame(coef_rows)
    top = coef_df.reindex(coef_df["coef_std"].abs().sort_values(ascending=False).index).head(16)
    report.append(top.to_markdown(index=False))
    report.append("")
    report.append(
        "Interpretation: OLS is used for mechanism direction and significance; "
        "linear/tree models are compared with country-group cross-validation for generalization."
    )
    (REPORTS / "course_ml_diagnostics_report.md").write_text("\n".join(report), encoding="utf-8")


if __name__ == "__main__":
    main()
